### PR TITLE
Closes AgileVentures/MetPlus_tracker#181

### PR DESCRIPTION
**Pull request by patmbolger**

### CODE REVIEW

**Comment by joaopapereira** [comment]
Don't we have unit tests for this feature?

**Comment by patmbolger** [comment]
No unit or functional tests for this.  I thought about but reached the conclusion that there were no functional tests that I could add that could not be done better as acceptance tests.  (no model or controller changes occurred - just behavior of Devise with resulting flash messages changing).

**Comment by joaopapereira** [comment]
I am ok with the answer with the answer, but in a usual context for modules changes we should have UT to check things out

**Comment by joaopapereira** [comment]
Going to merge this PR

**Pull request merged**
