### PR TITLE
SkillLevel model

### PR DESCRIPTION
**Pull request by patmbolger**
Closes AgileVentures/MetPlus_tracker#84

### CODE REVIEW

**Comment by joaopapereira** [comment]
Looks good, but i think we should add on the creation file some default values like:
Beginner
Intermediate
Expert

**Comment by patmbolger** [comment]
By "creation file" do you mean the migration file?

**Comment by joaopapereira** [comment]
Yes I do

**Comment by patmbolger** [comment]
Not sure what you mean .... we can only specify one default value on each column ... or is there some other mechanism you are referring to?

**Comment by patmbolger** [comment]
Added records create (beginner, etc....) to seeds.rb

**Comment by joaopapereira** [comment]
Looks good

**Pull request merged**
