### PR TITLE
replace "Not Available" with job seeker name, 

### LINKED ISSUE #740: everyone should be able to see job seekers names in match all
Client said that Agency Admin should be able to see all the names and cities to have overview of the whole system

Also that job developers should be able to see all this so they can forward them to another job developer - can't get detailed contact information, but can at least see name and city in order to facilitate discussion with other job developers

Also employers should have the ability to see job seeker names, city, job developer and degree of match but not contact details --> and employers can contact job developers, but not job seekers directly

So change desired here is to show the name (rather than "Not Available"), but just not link it to the job seeker details page

This is what it currently looks like:

Screenshot of PETS Cruncher 3-4-19

### PR DESCRIPTION
**Pull request by tansaku**
fixes AgileVentures/MetPlus_tracker#740

### CODE REVIEW

**Comment by tansaku** [comment]
@joaopapereira I removed my change and I still get this failure locallY :-(

```
  @javascript
  Scenario: Access job seeker job matching page                              # features/match_jobs_to_job_seeker.feature:42
    Given I am on the home page                                              # features/step_definitions/navigation_steps.rb:70
    And I login as "jane-dev@metplus.org" with password "qwerty123"          # features/step_definitions/devise_steps.rb:1
    And I should be on the Agency Person 'jane-dev@metplus.org' Home page    # features/step_definitions/navigation_steps.rb:74
    And I wait 2 seconds                                                     # features/step_definitions/web_steps.rb:88
    And I should see "Seeker, John"                                          # features/step_definitions/web_steps.rb:16
    And I should not see "No resume on file"                                 # features/step_definitions/web_steps.rb:16
    Then I press the Job Match button for 'john.seeker@gmail.com'            # features/step_definitions/navigation_steps.rb:82
    And I wait 5 seconds                                                     # features/step_definitions/web_steps.rb:88
    And I should be on the Job Seeker 'john.seeker@gmail.com' job match page # features/step_definitions/navigation_steps.rb:74
    And I should see "2.6 / 5.0" in the same table row as "c++ developer"    # features/step_definitions/web_steps.rb:56
      Unable to find visible css "tr" with text "c++ developer" (Capybara::ElementNotFound)
      features/match_jobs_to_job_seeker.feature:52:in `And I should see "2.6 / 5.0" in the same table row as "c++ developer"'
    And I click the "Hello, Jane" link                                       # features/step_definitions/web_steps.rb:96
    Then I logout                                                            # features/step_definitions/devise_steps.rb:13
    And I am logged in as "mark@metplus.org" with password "qwerty123"       # features/step_definitions/devise_steps.rb:1
    And I should be on the Agency Person 'mark@metplus.org' Home page        # features/step_definitions/navigation_steps.rb:74
    And I wait 2 seconds                                                     # features/step_definitions/web_steps.rb:88
    And I should see "Seeker, Tom"                                           # features/step_definitions/web_steps.rb:16
    And I should see "No resume on file"                                     # features/step_definitions/web_steps.rb:16

Failing Scenarios:
cucumber features/match_jobs_to_job_seeker.feature:42 # Scenario: Access job seeker job matching page

1 scenario (1 failed)
24 steps (1 failed, 7 skipped, 16 passed)
0m30.997s

```

```
cucumber features/match_jobs_to_job_seeker.feature:42
```

intermittent fail perhaps?

**Comment by joaopapereira** [comment]
@tansaku can you check to see what the page is displaying when the error happens?

**Comment by tansaku** [comment]
@joaopapereira with "show me the page" I see this:



That's for me locally on the development branch, and on the master branch

I see both development and master are green at the moment on CI, but my feature branch and development master all fail for me locally on the same point :-/

**Comment by joaopapereira** [comment]
@tansaku what is the cruncher that you are using when running locally?

**Comment by tansaku** [comment]
@joaopapereira I am not sure - I'm just running the cucumber test locally - does it not stub out the cruncher?   I have not tried connecting up to a local cruncher in dev mode - I am just using show my page from the cucumber tests to get the screen shot of what is shown.

Are the cucumber tests not stubbed out for a cruncher? do they rely on a particular remote cruncher setting?

**Comment by joaopapereira** [comment]
It does not stub out the cruncher it uses the one configured in `config/application.yml` under the variable `CRUNCHER_SERVICE_URL`

**Comment by joaopapereira** [comment]
If you think it is worth it you can use `https://github.com/AgileVentures/MetPlus_resumeCruncher/blob/development/docker-compose.yml` to stand up a local cruncher and change the configuration on `config/application.yml` to point to the image running in your machine

**Comment by tansaku** [comment]
thanks, so locally I have 

```
CRUNCHER_SERVICE_URL:      'https://pets-cruncher-dev.herokuapp.com/api/v99999'
```
which is the same as it is on the CI, but so the implication is that something has changed on the cruncher isn't it?

is the heroku cruncher being kept up to date with the new kotlin changes, or with any recent changes?

**Comment by joaopapereira** [comment]
@tansaku if you rebase the tests should pass now

**Comment by tansaku** [comment]
@joaopapereira just saw this - have rebased - will see if it builds - github used to give the admin option to do that rebasing of branches via the UI ...

**Review by joaopapereira — APPROVED** [review]
LGTM

**Comment by tansaku** [comment]
thanks for merging @joaopapereira :-)

**Pull request merged**
