### PR TITLE
Closes AgileVentures/MetPlus_tracker#210

### PR DESCRIPTION
**Pull request by patmbolger**
This is the job_category "delete" feature.

### CODE REVIEW

**Comment by joaopapereira** [comment]
Generally looks good, but I am afraid we are starting to have some code in JavaScript and we are not testing it thoroughly. Maybe we should start using Jasmine to test JavaScript parts as well

**Comment by patmbolger** [comment]
I agree we need to start doing functional tests with Jasmine.  

How about I create a separate story for that and we merge this PR now.  I want to get job_categories in place so that development of jobs can continue without interruption.

**Comment by joaopapereira** [comment]
Just wanted to point this out, but for next PR's I believe we should start doing so

**Comment by joaopapereira** [comment]
Going to merge the PR

**Pull request merged**
