### PR TITLE
Job seeker status field #142

### PR DESCRIPTION
**Pull request by vijayakarumudi**
Closes AgileVentures/MetPlus_tracker#182
Browsers compatibility in JS Registration and issue related to the style sheets

### CODE REVIEW

**Comment by vijayakarumudi** [comment]
agency_admin feature is failed

**Comment by vijayakarumudi** [comment]
close the pull request

**Comment by vijayakarumudi** [comment]
The closed the PR and  Reopened  the PR  again the agency_admin feature is failed.

**Comment by patmbolger** [comment]
I don't know if this is associated with the CI test failure (does not appear likely), but this PR contains 3 files that start with the string '.goutputstream'.  I think this might be related to a Ubuntu bug.  Please  remove those and resubmit.

**Comment by vijayakarumudi** [comment]
This PR for review

**Comment by patmbolger** [comment]
PR looks good to me.

**Comment by joaopapereira** [comment]
Looks good, going to merge

**Pull request merged**
