### PR TITLE
Closes AgileVentures/MetPlus_tracker#358

### PR DESCRIPTION
**Pull request by patmbolger**
This is based upon code in PR #304 (waffle 357).

That should be merged first and then this can be rebased.

Changes:

- [x] Presentation of information in horizontal table ala agency person view
- [x] If agency admin or company admin, include button 'Edit Person'
- [x] If agency admin, include button 'Delete Person'
- [x] If company admin, include button 'Delete Person' unless person shown is current user

### CODE REVIEW

**Comment by joaopapereira** [comment]
Lets wait on the 304 to be merge to review this

**Comment by joaopapereira** [comment]
Please rebase this PR

**Comment by patmbolger** [comment]
Rebased.

**Comment by joaopapereira** [comment]
Looks good, going to merge

**Pull request merged**
