### PR TITLE
Update user fields 

### PR DESCRIPTION
**Pull request by amba178**

### CODE REVIEW

**Comment by joaopapereira** [comment]
Does this close the issue 111?
The is no comment nor relation there.please change the name of the PR

**Comment by amba178** [comment]
It is issue#111. Do you want me to name:
Related AgileVentures/MetPlus_tracker#111.

**Comment by amba178** [comment]
or to title of issue: update user fields

**Comment by patmbolger** [comment]
Salem - this page describes some of the background for the naming convention of PRs: https://help.github.com/articles/closing-issues-via-commit-messages/

It is important to use one of the "closing" keywords, which is why the naming convention is:

    Closes AgileVentures/MetPlus_tracker#111

I have updated the wiki page "developing a feature" to reflect this.

**Pull request closed without merging**
