### PR TITLE
Closes AgileVentures/MetPlus_tracker#196

### PR DESCRIPTION
**Pull request by patmbolger**
This PR is based on changes in PR #180 - that PR should be merged first (and I may have merge conflicts in this PR as a result).

### CODE REVIEW

**Comment by joaopapereira** [comment]
Is there any fierce between the PR?

**Comment by patmbolger** [comment]
I don't understand your comment (?)

**Comment by joaopapereira** [comment]
can you please rebase and reopen so i can see the changes you made?
thanks

**Comment by patmbolger** [comment]
Merged with upstream dev.  Good to go now.

**Comment by joaopapereira** [comment]
Looks good

**Pull request merged**
