### PR TITLE
Update UI design and stylesheets

### PR DESCRIPTION
**Pull request by lollypop27**
**Story:** https://waffle.io/AgileVentures/MetPlus_tracker/cards/5878904d9d0c9f910011cad3

Update UI design on home page

### CODE REVIEW

**Comment by lollypop27** [comment]
@patmbolger I can't get my bottom right block to line up to the top.

**Comment by lollypop27** [comment]
@hin101 can you please have a look at my css on the blocks of the home page, I can't get the bottom right block to align to the top with the left block.

**Comment by patmbolger** [comment]
The text under "Register as an Employer" is running over the end of the gray background and also intersecting with the footer.  I see this in Safari and Chrome (have not checked other browsers):

screen shot 2017-01-27 at 9 58 09 am

**Comment by patmbolger** [comment]
Also, please note that the CI tests are failing because of the UI changes to the home page.  We need to change wording to reflect that words in the new design, and the links to register as a company or as a job seeker needed to also work.

**Comment by lollypop27** [comment]
@patmbolger thanks I will test in all browsers and fix. As well as fix failing test issues

**Comment by lollypop27** [comment]
@patmbolger Block have been fixed, hopefully will pass

**Comment by patmbolger** [comment]
Looks great .... merging now.

**Pull request merged**
