### PR TITLE
Feature/issue #70

### PR DESCRIPTION
**Pull request by amba178**

### CODE REVIEW

**Comment by joaopapereira** [comment]
Why is the JS status in this PR?

**Comment by joaopapereira** [comment]
And missing the JobSeeker
 - Connection between JS and JD
 - Connection between JS and CM

**Comment by joaopapereira** [comment]
We are missing also the Model AgencyPerson that will be used in the table Agency agency_people_job_seekers

**Comment by joaopapereira** [comment]
Please review the previous comments. and push a new version

**Comment by amba178** [comment]
I have combined AgencyPerson model  with AP<>JS joint table, eventhough it is separate task.  I will PR as issue#70

**Comment by patmbolger** [comment]
Salem - I think we collided here .... I just created a PR for AgencyPerson model (Waffle issue 76, PR #78.

**Pull request closed without merging**
