### PR TITLE
Closes AgileVentures/MetPlus_tracker#137

### PR DESCRIPTION
**Pull request by patmbolger**
This PR also includes changes from PR #133 - that PR should be merged before this one.

### CODE REVIEW

**Comment by joaopapereira** [comment]
I will review this change after the PR #133 is merged

**Comment by joaopapereira** [comment]
Need a rebase in this PR

**Comment by patmbolger** [comment]
I rebased and update the PR.  There are quite a few files showing up as changed that I did not touch (e.g., some .coffee files).

**Comment by joaopapereira** [comment]
Can you try to create a new PR using your change to see if it solves this issue, or pickup your diff and reapply it??

**Pull request closed without merging**
