### PR TITLE
Closes AgileVentures/MetPlus_tracker#449

### PR DESCRIPTION
**Pull request by patmbolger**
For certain (most) forms, the 'Cancel' button should return the user back to the previous view.

### CODE REVIEW

**Comment by joaopapereira** [comment]
@patmbolger Should we have some tests to ensure the correctness of the behavior?

**Comment by patmbolger** [comment]
I will a couple of tests for this behavior.

**Comment by patmbolger** [comment]
Added some accept tests for form cancel behavior.

**Comment by joaopapereira** [comment]
Going to merge

**Pull request merged**
