### PR TITLE
Update rails to 4.2.10

### PR DESCRIPTION
**Pull request by joaopapereira**

### CODE REVIEW

**Comment by patmbolger** [comment]
This looks good. Should we go ahead and merge or did you want to address the remaining Hound violations?

Also, we should work on moving to rails 5.x.  Do you agree?

**Comment by joaopapereira** [comment]
@patmbolger I am not sure how to split the regex into multiple lines.
This is an intermediary step to 5. Now that we are in the latest 4 we should have a smooth ride to 5

**Comment by patmbolger** [comment]
Yes, thats a pain ... lets not worry about it.  We can merge this after we fix that production bug.

**Comment by patmbolger** [comment]
All tests pass for me (locally).  Merging.

**Pull request merged**
