### PR TITLE
Jobs view to search jobs #514

### PR DESCRIPTION
**Pull request by pcaston**
Swapped out views/jobs/index.html.haml with  list_search_jobs.html.haml.
Removed list_search_jobs method and placed functionality under index method.
Added hide/show toggle for jobs search form.
Added instructions to click on column title to search depending on number of jobs returned being > 1.

### CODE REVIEW

**Comment by pcaston** [comment]
Fixing some of the HoundCi issues.

**Comment by pcaston** [comment]
Re-open Pull request after fixes

**Comment by patmbolger** [comment]
Please rebase against upstream/development - looks like you've got an older version of some of the cucumber tests and that is why some of those are failing.

**Comment by pcaston** [comment]
Closing and Reopenning to re-run semaphore tests after re-basing.

**Comment by pcaston** [comment]
Fixing jobs.feature tests

**Pull request closed without merging**
