### PR TITLE
Closes AgileVentures/MetPlus_tracker#367

### PR DESCRIPTION
**Pull request by dsmegha**
Added a new file app/validators/fax_validator.rb, which validates the fax number through a regex.

Changed Company and Agency models to use the new validator for fax.

Added placeholders in the Company and Agency forms to help user know what a valid acceptable fax is.

Changed the spec/models/company_spec.rb to test the newly made changes.

### CODE REVIEW

**Comment by joaopapereira** [comment]
I think it looks good, can you please add tests to the Agency as well?

**Comment by patmbolger** [comment]
I reviewed and it looks great.  Agree with the suggestion to add format tests to agency_spec.rb.

**Comment by dsmegha** [comment]
Added tests to validate the email, phone, fax and Website in the agency model.

**Comment by patmbolger** [comment]
Looks good!

**Comment by joaopapereira** [comment]
Looks good, didn't realize we were missing all the tests in Agency :( 
Good you caught that up.

**Comment by joaopapereira** [comment]
Going to merge the code

**Pull request merged**
