### PR TITLE
closes AgileVentures/MetPlus_tracker#96

### PR DESCRIPTION
**Pull request by patmbolger**
Configured ActionMailer for use by the 'devise' gem

Added 'figaro' gem to manage env-specific, and sensitive, config data (see config/application.yml.example)

Added Main controller skeleton (just sufficient to start testing Devise account confirmation via email)

### CODE REVIEW

**Comment by joaopapereira** [comment]
You didnt need to do any change in the test environment file?

**Comment by patmbolger** [comment]
No tests yet, unfortunately.  I was hurrying to get this ready so that we have a chance of showing the client registration/login/logout features on Friday.

I intend to deliver tests (will add an issue for that).

**Comment by patmbolger** [comment]
On second thought, 'm not sure what I would test here.  I am using Devise code (even their Mailer class) and would be testing Devise functionality that the gem developers have already tested.

When we add our own Mailer we will definitely need tests (spec and cucumber).

**Comment by joaopapereira** [comment]
I believe we should have 2 different PRs for this. But going to merge due to the urgency

**Pull request merged**
